   - name: install java
     package:
      name: java
      state: present
  
   - name: add application user
     user:
      name: "{{user}}"
      comment: student

   - name: download and extract tomcat
     unarchive:
      src: "{{tomcat_url}}"
      dest: /opt/tomcat
     become_user: "{{user}}"

   - name: find old directories
     find: 
      path: /home/{{user}}/{{tomact_file_name}}/webapps
      file_type: any
     register: out

   - name: dlete finded directories
     files:
      path: "{{item.path}}"
      state: absent
     loop: "{{out.files}}"
     

 
   - name:  download the war file
     get_url:
      url: "${{war_url}}"
      dest: /home/{{user}}/{{tomact_file_name}}/webapps/student.war

   - name: download 
