   - name: install java
     package:
      name: java
      state: present
  
   - name: add application user
     user:
      name: "{{user}}"
      comment: student

   - name: download and extract tomcat
     unarchive:
      src: "{{tomcat_url}}"
      dest: /opt/tomcat
      become_user: 
