- name: installing application server
  hosts: all
  become: yes
  tasks:
   - name: install java
     package:
      name: java
      state: present
  
   - name: add application user
     user:
      name: "{{user}}"
      
