- name: encrypting the file
  hosts: all
  tasks:
   - name: printing mssg on the terminal
     debug:
      msg: hello how r u





#encrypting the .yaml file using ansible-vault feature
# ansible-vault encrypt playbooks/ansible-vault-filelevel.yaml
#above command encrypts the yaml file
# ansible-playbook playbooks

   
  