- name: find the files in given directory and remove them
  hosts: all
  tasks:
   - name: find the files
     find:
      paths: /tmp/demo
      recurse: yes
      file_type: any
    register: out
  
   - name: output files in directory
     debug:
      msg: "{{out}}"

   - name: delete files in the directory
     file: 
      path: "{{item.path}}"
      state: absent
     loop: "{{out.files}}"