- name: find the files in given directory and remove them
  hosts: all
  tasks:
   - name: find the files
     find:
      paths: /tmp/demo
      recurse: yes
      file_type
    register: out

   - name: output files in directory
     debug:
      msg: "{{out}}"