- name: testing the return code
  hosts: all
  tasks:
  - name: check directory exists or not
     command: ls -ltr /tmp/test123
     register: OUT
  

   - name: return value check
     debug:
      msg: "{{OUT.rc}}"  
  
   - name: command result failed when rc!=0
     debug:
      msg: script ddint get executed succesfully
     failed_when: OUT.rc > 0


   - name: creating a directory
     file:
      path: /tmp/manikanta
      state: directory
      
      