- name: testing the return code
  hosts: all
  tasks:
   - name: delete a directory 
     file:
      path: /tmp/test123
      state: absent
      register: OUT
      failed_when: current_version.rc == 2 