- name: defining and accessing variables
  hosts: all
  vars:
    URL: google.com
  tasks:
   - name: acessing variable define @ file level
     debug:
      msg: the url is - {{URL}}
  
   - name: accessing varibales define with in the task
     debug:
      msg: the url is - {{URL}}
     vars:
       URL: yahoo.com